name: covidashboard
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.2=py38h2a96729_1
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py38haa95532_0
  - intel-openmp=2021.3.0=haa95532_3372
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.0=py38h277e83a_2
  - mkl_random=1.2.2=py38hf11a4ad_0
  - numexpr=2.7.3=py38hb80d3ca_1
  - numpy=1.20.3=py38ha4e8547_0
  - numpy-base=1.20.3=py38hc2deb75_0
  - openssl=1.1.1l=h2bbff1b_0
  - pandas=1.3.2=py38h6214cd6_0
  - pip=21.0.1=py38haa95532_0
  - plotly=5.1.0=pyhd3eb1b0_0
  - python=3.8.11=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - setuptools=52.0.0=py38haa95532_0
  - six=1.15.0=py38haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - tenacity=6.3.1=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
